[global]
pid = /var/run/php-fpm.pid
error_log = /var/log/supervisor/php-fpm-error.log
daemonize = no

[www]
user = nginx
group = nginx

listen = /var/run/php-fpm.sock
listen.owner = nginx
listen.group = nginx
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests = 500

clear_env = no
catch_workers_output = yes
